[theme]
primaryColor = "#3E8E41"
font = "sans serif"

[theme.light]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F0"
textColor = "#1C2420"

[theme.dark]
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1C2420"
textColor = "#FAFAFA"
